name = "Entropia"
uuid = "1a82f0b4-7a6b-4d0c-8734-8f44131a69e4"
authors = ["Juan Luis Barbería"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
